# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(default='direccion', max_length=10)),
                ('genero', models.CharField(choices=[('f', 'masculino'), ('m', 'femenino')], max_length=10)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.CharField(blank=True, max_length=15, null=True)),
                ('docente', models.CharField(max_length=30)),
            ],
        ),
    ]
