# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='creditos',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='docente',
        ),
        migrations.AddField(
            model_name='materia',
            name='cupo',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
